// 登录相关
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILULE = 'LOGIN_USER_FAILULE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const CHANGE_LOGIN_NAME = 'CHANGE_LOGIN_NAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'
