// 登录相关
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const CHANGE_LOGIN_NAME = 'CHANGE_LOGIN_NAME'
export const CHANGE_LOGIN_PASSWORD = 'CHANGE_LOGIN_PASSWORD'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'


//数据列表
export const FETCH_LIST_REQUEST = 'FETCH_LIST_REQUEST'
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS'
export const FETCH_LIST_FAILURE = 'FETCH_LIST_FAILURE'
export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAILURE = 'ADD_ITEM_FAILURE'
export const SHOW_MODAL = 'SHOW_MODAL'
